app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
pageNotFound:
    pattern:  /{path}
    defaults: { _controller: AppBundle:Default:pageNotFound, path: '' }
    requirements:
        path: .*