# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_CLIENTE
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/banear, role: ROLE_ADMIN }
        - { path: ^/platos, role: ROLE_ADMIN }
        - { path: ^/borrar, role: ROLE_ADMIN }
        - { path: ^/eliminartodo, role: ROLE_ADMIN }
        - { path: ^/modificartipo, role: ROLE_ADMIN }
        - { path: ^/locales, role: ROLE_ADMIN }
        - { path: ^/local, role: ROLE_CLIENTE }
        - { path: ^/usuario, role: ROLE_CLIENTE }
        - { path: ^/tooglelocal, role: ROLE_CLIENTE }
        - { path: ^/reclamar, role: ROLE_CLIENTE }
        - { path: ^/articulos, role: ROLE_CLIENTE }
        - { path: ^/registrararticulos, role: ROLE_CLIENTE }
        - { path: ^/local, role: ROLE_CLIENTE }
        - { path: ^/registrarlocal, role: ROLE_CLIENTE }
        - { path: ^/modificarlocal, role: ROLE_CLIENTE }
        - { path: ^/menus, role: ROLE_CLIENTE }
        - { path: ^/registrarmenu, role: ROLE_CLIENTE }
        - { path: ^/modificarmenu, role: ROLE_CLIENTE }
        - { path: ^/modificararticulo, role: ROLE_CLIENTE }
        - { path: ^/eliminararticulo, role: ROLE_CLIENTE }
        - { path: ^/eliminarmenu, role: ROLE_CLIENTE }
        - { path: ^/comentarios, role: ROLE_CLIENTE }